/** Brinkbound — original platform-fighter roster (not Nintendo IP) */

export const STOCKS = 3;

export const ROSTER = [
  {
    id: "seraphine",
    name: "Seraphine Vale",
    title: "The Broken Halo",
    portrait: "/roster/heroine_seraphine.png",
    skin: 0xf0d5c4,
    hair: 0xe8eef5,
    accent: 0xd4af37,
    outfit: 0xf5f5f0,
    secondary: 0xc9a227,
    eye: 0x2ec4b6,
    height: 1.0,
    weight: 0.95,
    speed: 1.05,
    power: 1.1,
    lore: "Cast down from the Sky Choir for refusing an unjust purge. She fights to earn a new name on the lip of every table she lands on.",
    style: "Heavy aerials, golden smash bursts",
    hairStyle: "wave",
  },
  {
    id: "nyx",
    name: "Nyx Hollow",
    title: "Void Pocket",
    portrait: "/roster/heroine_nyx.png",
    skin: 0x3b2418,
    hair: 0x6b2d8b,
    accent: 0xb967ff,
    outfit: 0x121212,
    secondary: 0x2a1038,
    eye: 0xf0c24b,
    height: 0.96,
    weight: 0.88,
    speed: 1.2,
    power: 0.95,
    lore: "A thief who steals moments, not jewels. If you blinked on the brink, she already moved your stock.",
    style: "Speed, mixups, vanish-step specials",
    hairStyle: "undercut",
  },
  {
    id: "kaede",
    name: "Kaede Rin",
    title: "Crimson Interval",
    portrait: "/roster/heroine_kaede.png",
    skin: 0xe6b89c,
    hair: 0x1a1a1a,
    accent: 0xc41e3a,
    outfit: 0x1c1010,
    secondary: 0x8b0000,
    eye: 0xffb347,
    height: 0.98,
    weight: 0.92,
    speed: 1.15,
    power: 1.05,
    lore: "Duelist of the Interval School. She times her blade between heartbeats — and between ledge techs.",
    style: "Precise tilts, lethal forward-smash",
    hairStyle: "ponytail",
  },
  {
    id: "vexa",
    name: "Vexa Coil",
    title: "Shopfloor Sovereign",
    portrait: "/roster/heroine_vexa.png",
    skin: 0xc68642,
    hair: 0xb85c38,
    accent: 0xff6a00,
    outfit: 0xd35400,
    secondary: 0x4a3728,
    eye: 0x4fc3f7,
    height: 0.97,
    weight: 1.08,
    speed: 0.95,
    power: 1.2,
    lore: "Union enforcer turned arena wrecker. Her gauntlet once tightened bolts. Now it loosens teeth.",
    style: "Armor breaks, wrench spike, high knockback",
    hairStyle: "coils",
  },
  {
    id: "maris",
    name: "Maris Tide",
    title: "Pressure Saint",
    portrait: "/roster/heroine_maris.png",
    skin: 0x8d5524,
    hair: 0x0d7377,
    accent: 0x7ef9e4,
    outfit: 0x145a66,
    secondary: 0x0a3a40,
    eye: 0xa8e6cf,
    height: 1.02,
    weight: 1.05,
    speed: 1.0,
    power: 1.08,
    lore: "Born under crushing deep pressure, she treats air combat like swimming — patient, then sudden.",
    style: "Floaty recovery, tidal sweep special",
    hairStyle: "braids",
  },
  {
    id: "orielle",
    name: "Orielle Lux",
    title: "Gilded Vein",
    portrait: "/roster/heroine_orielle.png",
    skin: 0xd4a574,
    hair: 0xe6c35c,
    accent: 0x0b6e4f,
    outfit: 0x1a1a1a,
    secondary: 0x0b6e4f,
    eye: 0x2ecc71,
    height: 1.01,
    weight: 0.9,
    speed: 1.1,
    power: 1.0,
    lore: "Court assassin who defected mid-waltz. Every polite bow hides a kill confirm.",
    style: "Fencing range, elegant pierce smash",
    hairStyle: "curls",
  },
  {
    id: "rhea",
    name: "Rhea Ashwind",
    title: "Sun-Writ",
    portrait: "/roster/heroine_rhea.png",
    skin: 0xb66a3c,
    hair: 0x6b2d1a,
    accent: 0xf4c430,
    outfit: 0xf3ece0,
    secondary: 0xb08d57,
    eye: 0xffd166,
    height: 1.03,
    weight: 1.12,
    speed: 0.9,
    power: 1.25,
    lore: "War-priest of the Ashwind dunes. Her scripture is simple: stand, strike, refuse the fall.",
    style: "Super armor bursts, holy slam",
    hairStyle: "locs",
  },
  {
    id: "ivy",
    name: "Ivy Crag",
    title: "Trailwreck",
    portrait: "/roster/heroine_ivy.png",
    skin: 0xf3d1b8,
    hair: 0x3f6b3a,
    accent: 0x8fbc8f,
    outfit: 0x3e4a34,
    secondary: 0x6b4f3a,
    eye: 0x7cfc00,
    height: 0.95,
    weight: 1.15,
    speed: 0.92,
    power: 1.18,
    lore: "Mountain guide who lost a whole expedition to a sinkhole — and learned to punch geology back.",
    style: "Clinch grabs, ground pound, ledge bully",
    hairStyle: "bob",
  },
  {
    id: "lune",
    name: "Lune Petal",
    title: "Soft Lock",
    portrait: "/roster/heroine_lune.png",
    skin: 0xffe4e1,
    hair: 0xc8a2c8,
    accent: 0xff69b4,
    outfit: 0xe6d5f2,
    secondary: 0x9b7bb8,
    eye: 0xff8fab,
    height: 0.93,
    weight: 0.85,
    speed: 1.18,
    power: 0.9,
    lore: "Looks like a bakery shift lead. Grapples like a hydraulic press. Smile is the setup.",
    style: "Command grabs, moon-bounce recovery",
    hairStyle: "long",
  },
  {
    id: "cass",
    name: "Cass Terrax",
    title: "Reentry",
    portrait: "/roster/heroine_cass.png",
    skin: 0x5c3317,
    hair: 0x0a0a0a,
    accent: 0x00e5ff,
    outfit: 0xf2f5f7,
    secondary: 0x1a3a4a,
    eye: 0x00bcd4,
    height: 0.99,
    weight: 0.98,
    speed: 1.08,
    power: 1.02,
    lore: "Orbital courier who missed her drop window and made the table her new LZ. Precision under spin.",
    style: "Dash attacks, magnet boots, laser tilt",
    hairStyle: "pixie",
  },
];

export function getFighter(id) {
  return ROSTER.find((f) => f.id === id) || ROSTER[0];
}
